##
## Test Suites
##

    modified.files.includes[relevant][portal-db-schema-definition-test-rule]=**

    relevant.rule.names=\
        portal-db-schema-definition-test-rule

    test.batch.names[relevant][portal-db-schema-definition-test-rule]=\
        functional-tomcat90-postgresql155-jdk8

    #
    # Portal Hotfix Release
    #

    test.batch.run.property.query[functional-bundle-tomcat-postgresql155-jdk8][test-portal-hotfix-release]=\
        ${test.batch.run.property.query[functional-tomcat*-postgresql*-jdk8][relevant][portal-db-schema-definition-test-rule]}

    #
    # Relevant
    #

    test.batch.run.property.query[functional-tomcat*-postgresql*-jdk8][relevant][portal-db-schema-definition-test-rule]=\
        (testray.main.component.name == "Database Upgrade Framework")

##
## Testray
##

    testray.main.component.name=Database Upgrade Framework