##
## Test Suites
##

    modified.files.includes[relevant][liferay-tryitnow-workspace-rule]=**

    relevant.rule.names=\
        liferay-tryitnow-workspace-rule

    test.batch.names[relevant][liferay-tryitnow-workspace-rule]=\
        functional-tomcat90-postgresql155-jdk8,\
        functional-workspaces-bundle-postgresql155-jdk8

    #
    # Portal Hotfix Release
    #

    test.batch.run.property.query[functional-bundle-tomcat-postgresql155-jdk8][test-portal-hotfix-release]=\
        ${test.batch.run.property.query[functional-tomcat*-postgresql*-jdk8][relevant][liferay-tryitnow-workspace-rule]}

    #
    # Relevant
    #

    test.batch.run.property.query[functional-tomcat*-postgresql*-jdk8][relevant][liferay-tryitnow-workspace-rule]=\
        (testray.main.component.name ~ "Liferay Sample Workspace")

    test.batch.run.property.query[functional-workspaces-bundle-postgresql*-jdk8][relevant][liferay-tryitnow-workspace-rule]=\
        (testray.main.component.name ~ "Liferay Sample Workspace")

##
## Testray
##

    testray.main.component.name=Liferay Sample Workspace