##
## Test Suites
##

    modified.files.includes[relevant][sharepoint-rest-rule]=**

    relevant.rule.names=\
        sharepoint-rest-rule

    test.batch.names[relevant][sharepoint-rest-rule]=\
        functional-tomcat90-postgresql155-jdk8,\
        modules-integration-postgresql155-jdk8,\
        modules-unit-jdk8

    #
    # Portal Hotfix Release
    #

    test.batch.run.property.query[functional-bundle-tomcat-postgresql155-jdk8][test-portal-hotfix-release]=\
        ${test.batch.run.property.query[functional-tomcat*-postgresql*-jdk8][relevant][sharepoint-rest-rule]}

    #
    # Relevant
    #

    modules.includes.required.test.batch.class.names.includes[modules-integration-postgresql155-jdk8][relevant][sharepoint-rest-rule]=\
        dxp/apps/sharepoint-rest/**/*Test.java

    modules.includes.required.test.batch.class.names.includes[modules-unit-jdk8][relevant][sharepoint-rest-rule]=\
        dxp/apps/sharepoint-rest/**/*Test.java

    test.batch.run.property.query[functional-tomcat*-postgresql*-jdk8][relevant][sharepoint-rest-rule]=\
        (osgi.modules.includes ~ "sharepoint-rest") AND \
        (portal.acceptance == true)

##
## Testray
##

    testray.main.component.name=External Document Repositories