##
## Test Suites
##

    modified.files.includes[relevant][portal-rule]=**

    relevant.rule.names=\
        portal-rule

    test.batch.names[relevant][portal-rule]=\
        modules-integration-postgresql155-jdk8,\
        modules-unit-jdk8

    #
    # Relevant
    #

    modules.includes.required.test.batch.class.names.includes[modules-integration-postgresql155-jdk8][relevant][portal-rule]=\
        dxp/apps/portal/**/*Test.java

    modules.includes.required.test.batch.class.names.includes[modules-unit-jdk8][relevant][portal-rule]=\
        dxp/apps/portal/**/*Test.java

##
## Testray
##

    testray.main.component.name=Portal Services