##
## Test Suites
##

    modified.files.includes[relevant][portlet-display-template-rule]=**

    relevant.rule.names=\
        portlet-display-template-rule

    test.batch.names[relevant][portlet-display-template-rule]=\
        modules-integration-mysql57,\
        modules-unit

    #
    # Relevant
    #

    modules.includes.required.test.batch.class.names.includes[modules-integration-mysql57][relevant][portlet-display-template-rule]=\
        apps/portal-display-template/**/*Test.java

    modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][portlet-display-template-rule]=\
        apps/portal-display-template/**/*Test.java

##
## Testray
##

    testray.main.component.name=Widget Page Templates