##
## Test Suites
##

    modified.files.includes[relevant][util-rule]=**

    relevant.rule.names=\
        util-rule

    test.batch.names[relevant][util-rule]=\
        functional-tomcat90-postgresql155-jdk8

    #
    # Relevant
    #

    test.batch.run.property.query[functional-tomcat*-postgresql*-jdk8][relevant][util-rule]=\
        (testray.main.component.name == "Locale")