##
## Test Suites
##

    modified.files.includes[relevant][frontend-js-walkthrough-web-rule]=**

    relevant.rule.names=\
        frontend-js-walkthrough-web-rule

    test.batch.names[relevant][frontend-js-walkthrough-web-rule]=\
        functional-tomcat90-postgresql155-jdk8

    #
    # Portal Hotfix Release
    #

    test.batch.run.property.query[functional-bundle-tomcat-postgresql155-jdk8][test-portal-hotfix-release]=\
        ${test.batch.run.property.query[functional-tomcat*-postgresql*-jdk8][relevant][frontend-js-walkthrough-web-rule]}

    #
    # Relevant
    #

    test.batch.run.property.query[functional-tomcat*-postgresql*-jdk8][relevant][frontend-js-walkthrough-web-rule]=\
        (testray.component.names ~ "Walkthrough") AND \
        (\
            (portal.acceptance == true) AND \
            (portal.upstream == true)\
        ) AND \
        (\
            (app.server.types == null) OR \
            (app.server.types ~ "tomcat")\
        ) AND \
        (\
            (database.types == null) OR \
            (database.types ~ "postgresql")\
        )

##
## Testray
##

    testray.main.component.name=User Interface