##
## Test Suites
##

    modified.files.includes[relevant][portal-search-similar-results-rule]=**

    relevant.rule.names=\
        portal-search-similar-results-rule

    test.batch.names[relevant][portal-search-similar-results-rule]=\
        functional-tomcat90-postgresql155-jdk8,\
        functional-upgrade-tomcat90-postgresql155-jdk8,\
        modules-integration-postgresql155-jdk8,\
        modules-unit-jdk8

    #
    # Portal Hotfix Release
    #

    test.batch.run.property.query[functional-bundle-tomcat-postgresql155-jdk8][test-portal-hotfix-release]=\
        ${test.batch.run.property.query[functional-tomcat*-postgresql*-jdk8][relevant][portal-search-similar-results-rule]}

    #
    # Relevant
    #

    modules.includes.required.test.batch.class.names.includes[modules-integration-postgresql155-jdk8][relevant][portal-search-similar-results-rule]=\
        dxp/apps/portal-search-similar-results/**/*Test.java

    modules.includes.required.test.batch.class.names.includes[modules-unit-jdk8][relevant][portal-search-similar-results-rule]=\
        dxp/apps/portal-search-similar-results/**/*Test.java

    test.batch.run.property.query[functional-tomcat*-postgresql*-jdk8][relevant][portal-search-similar-results-rule]=\
        (portal.acceptance == true) AND \
        (portal.suite.search.engine ~ "elasticsearch7")

    test.batch.run.property.query[functional-upgrade-tomcat*-postgresql*-jdk8][relevant][portal-search-similar-results-rule]=\
        (portal.suite.search.engine ~ "elasticsearch7") AND \
        (testray.main.component.name ~ "Upgrades Search")

##
## Testray
##

    testray.main.component.name=Elasticsearch Impl