##
## Test Suites
##

    modified.files.includes[relevant][account-rule]=**

    relevant.rule.names=\
        account-rule

    test.batch.names[relevant][account-rule]=\
        functional-tomcat90-postgresql155-jdk8,\
        functional-upgrade-tomcat90-postgresql155-jdk8,\
        modules-integration-postgresql155-jdk8,\
        modules-unit-jdk8

    #
    # Portal Hotfix Release
    #

    test.batch.run.property.query[functional-bundle-tomcat-postgresql155-jdk8][test-portal-hotfix-release]=\
        ${test.batch.run.property.query[functional-tomcat*-postgresql*-jdk8][relevant][account-rule]}

    #
    # Relevant
    #

    modules.includes.required.test.batch.class.names.includes[modules-integration-postgresql155-jdk8][relevant][account-rule]=\
        apps/account/**/*Test.java

    modules.includes.required.test.batch.class.names.includes[modules-unit-jdk8][relevant][account-rule]=\
        apps/account/**/*Test.java

    test.batch.run.property.query[functional-tomcat*-postgresql*-jdk8][relevant][account-rule]=\
        (portal.acceptance == true) AND \
        (\
            (testray.component.names ~ "Account") OR \
            (testray.main.component.name ~ "Account")\
        )

    test.batch.run.property.query[functional-upgrade*-tomcat*-postgresql*-jdk8][relevant][account-rule]=\
        (portal.acceptance == true) AND \
        (testray.component.names ~ "Account")

##
## Testray
##

    testray.main.component.name=Account