##
## Playwright
##

    playwright.test.project[playwright-js-tomcat90-postgresql155-jdk8][relevant][frontend-editor-rule]=frontend-editor-ckeditor-sample-web

##
## Relevant
##

    modules.includes.required.test.batch.class.names.includes[modules-integration-postgresql155-jdk8][relevant][frontend-editor-rule]=

    modules.includes.required.test.batch.class.names.includes[modules-unit-jdk8][relevant][frontend-editor-rule]=

    test.batch.run.property.query[frontend-editor-rule][relevant][functional-tomcat90-postgresql155-jdk8]=

##
## Test Suites
##

    modified.files.includes[relevant][frontend-editor-rule]=**

    relevant.rule.names=\
        frontend-editor-rule

    test.batch.names[relevant][frontend-editor-rule]=\
        playwright-js-tomcat90-postgresql155-jdk8

##
## Testray
##

    testray.main.component.name=WYSIWYG